name: apollo

services:
  api:
    build:
      context: .
      target: dev
    working_dir: /app
    environment:
      APOLLO__PORT: 3000
      APOLLO__HOST: http://localhost
      APOLLO__TOKEN: 123aAxZc&6V!
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    entrypoint: npm run watch
volumes:
  node_modules: